// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYIjjBxBaGfvkK1cTBE7ALIEK--MemZSI',
    appId: '1:439824774720:web:d7bc6b451092def07691a5',
    messagingSenderId: '439824774720',
    projectId: 'carinfo-62bd5',
    authDomain: 'carinfo-62bd5.firebaseapp.com',
    storageBucket: 'carinfo-62bd5.appspot.com',
    measurementId: 'G-KBE7VTR2H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ou8Xozrb5aN8zh5hK5R6LbORm669CVY',
    appId: '1:439824774720:android:d40a1ee3ad952a717691a5',
    messagingSenderId: '439824774720',
    projectId: 'carinfo-62bd5',
    storageBucket: 'carinfo-62bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-5Iwy1e5lXQ9LnaXQhgQYUSnvvl9m8k',
    appId: '1:439824774720:ios:81c4a9a3becbb6cf7691a5',
    messagingSenderId: '439824774720',
    projectId: 'carinfo-62bd5',
    storageBucket: 'carinfo-62bd5.appspot.com',
    iosBundleId: 'com.example.carInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-5Iwy1e5lXQ9LnaXQhgQYUSnvvl9m8k',
    appId: '1:439824774720:ios:81c4a9a3becbb6cf7691a5',
    messagingSenderId: '439824774720',
    projectId: 'carinfo-62bd5',
    storageBucket: 'carinfo-62bd5.appspot.com',
    iosBundleId: 'com.example.carInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYIjjBxBaGfvkK1cTBE7ALIEK--MemZSI',
    appId: '1:439824774720:web:e0d4893b04b2dc197691a5',
    messagingSenderId: '439824774720',
    projectId: 'carinfo-62bd5',
    authDomain: 'carinfo-62bd5.firebaseapp.com',
    storageBucket: 'carinfo-62bd5.appspot.com',
    measurementId: 'G-GBHFZGC4QF',
  );
}
